# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests and Lint

on:
  pull_request:

jobs:
  build:

    name: Test and Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@badgateway'
        node-version: ${{ matrix.node-version }}
    - name: Authenticate with github packages
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_KEY }}" >> ./.npmrc
    - name: Dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
